In [2]:
import numpy as np
import pandas as pd
#import matplotlib.

In [3]:
train_cmp=pd.read_csv("C:/Users/Mahavir/Desktop/Customer Value Prediction/Capstone Data/TrainPeople.csv",low_memory=False)
#C:\Users\Mahavir\Desktop\Customer Value Prediction\Capstone Data

In [5]:
train_cmp.head(3)

Unnamed: 0 people_id   activity_id  activity_category  char_1_x  char_2_x  \
0           0   ppl_100  act2_2434093                  2         0         0   
1           0   ppl_100  act2_3404049                  2         0         0   
2           0   ppl_100  act2_3651215                  2         0         0   

   char_3_x  char_4_x  char_5_x  char_6_x  ...    char_32  char_33  char_34  \
0         0         0         0         0  ...          0        0        1   
1         0         0         0         0  ...          0        0        1   
2         0         0         0         0  ...          0        0        1   

   char_35  char_36  char_37  char_38  year_y  month_y  day_y  
0        1        1        0       36    2021        6     29  
1        1        1        0       36    2021        6     29  
2        1        1        0       36    2021        6     29  

[3 rows x 60 columns]

In [7]:
train_cmp.columns

Index(['Unnamed: 0', 'people_id', 'activity_id', 'activity_category',
       'char_1_x', 'char_2_x', 'char_3_x', 'char_4_x', 'char_5_x', 'char_6_x',
       'char_7_x', 'char_8_x', 'char_9_x', 'char_10_x', 'outcome', 'year_x',
       'month_x', 'day_x', 'char_1_y', 'group_1', 'char_2_y', 'char_3_y',
       'char_4_y', 'char_5_y', 'char_6_y', 'char_7_y', 'char_8_y', 'char_9_y',
       'char_10_y', 'char_11', 'char_12', 'char_13', 'char_14', 'char_15',
       'char_16', 'char_17', 'char_18', 'char_19', 'char_20', 'char_21',
       'char_22', 'char_23', 'char_24', 'char_25', 'char_26', 'char_27',
       'char_28', 'char_29', 'char_30', 'char_31', 'char_32', 'char_33',
       'char_34', 'char_35', 'char_36', 'char_37', 'char_38', 'year_y',
       'month_y', 'day_y'],
      dtype='object')

In [9]:
np.count_nonzero(pd.isnull(train_cmp.outcome))

0

In [19]:
train_cmp.loc[train_cmp.group_1]>

Unnamed: 0   people_id   activity_id  activity_category  char_1_x  \
17304        1577  ppl_102957  act2_1107478                  3         0   
17304        1577  ppl_102957  act2_1107478                  3         0   
17304        1577  ppl_102957  act2_1107478                  3         0   
17304        1577  ppl_102957  act2_1107478                  3         0   
17304        1577  ppl_102957  act2_1107478                  3         0   
8688          772  ppl_101416  act2_2224710                  2         0   
8688          772  ppl_101416  act2_2224710                  2         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
33592        3038  ppl_105739  act2_1022838                  3         0   
...           ...         ...           ...                ...       ...   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685                  2         0   
20472        1908  ppl_103598  act2_3906685            

In [6]:
train_cmp.shape

(1999999, 60)

In [38]:
People.head()

people_id  char_1      group_1  char_2        date   char_3   char_4  \
0     ppl_100  type 2  group 17304  type 2  2021-06-29   type 5   type 5   
1  ppl_100002  type 2   group 8688  type 3  2021-01-06  type 28   type 9   
2  ppl_100003  type 2  group 33592  type 3  2022-06-10   type 4   type 8   
3  ppl_100004  type 2  group 22593  type 3  2022-07-20  type 40  type 25   
4  ppl_100006  type 2   group 6534  type 3  2022-07-27  type 40  type 25   

   char_5  char_6   char_7   ...    char_29 char_30  char_31  char_32  \
0  type 5  type 3  type 11   ...      False    True     True    False   
1  type 5  type 3  type 11   ...      False    True     True     True   
2  type 5  type 2   type 5   ...      False   False     True     True   
3  type 9  type 4  type 16   ...       True    True     True     True   
4  type 9  type 3   type 8   ...      False   False     True    False   

   char_33  char_34  char_35  char_36  char_37  char_38  
0    False     True     True     True    False       36  
1     True     True     True     True    False       76  
2     True     True    False     True     True       99  
3     True     True     True     True     True       76  
4    False    False     True     True    False       84  

[5 rows x 41 columns]

In [23]:
import matplotlib.pyplot as plt
%matplotlib inline

In [33]:
#plt.plot(People.group_1.unique())

In [3]:
People=pd.read_csv("C:/Users/Mahavir/Desktop/Customer Value Prediction/people.csv")

In [35]:
People.group_1.describe()

count          189118
unique          34224
top       group 17304
freq            77314
Name: group_1, dtype: object

In [37]:
People.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189118 entries, 0 to 189117
Data columns (total 41 columns):
people_id    189118 non-null object
char_1       189118 non-null object
group_1      189118 non-null object
char_2       189118 non-null object
date         189118 non-null object
char_3       189118 non-null object
char_4       189118 non-null object
char_5       189118 non-null object
char_6       189118 non-null object
char_7       189118 non-null object
char_8       189118 non-null object
char_9       189118 non-null object
char_10      189118 non-null bool
char_11      189118 non-null bool
char_12      189118 non-null bool
char_13      189118 non-null bool
char_14      189118 non-null bool
char_15      189118 non-null bool
char_16      189118 non-null bool
char_17      189118 non-null bool
char_18      189118 non-null bool
char_19      189118 non-null bool
char_20      189118 non-null bool
char_21      189118 non-null bool
char_22      189118 non-null bool
char_23      18

In [4]:
train=pd.read_csv("C:/Users/Mahavir/Desktop/Customer Value Prediction/train.csv",low_memory=False)

In [8]:
train.shape

(1999999, 16)

In [12]:
train.head(100)

Unnamed: 0   people_id   activity_id        date activity_category char_1  \
0            1     ppl_100  act2_2434093  2022-09-27            type 2    NaN   
1            2     ppl_100  act2_3404049  2022-09-27            type 2    NaN   
2            3     ppl_100  act2_3651215  2023-08-04            type 2    NaN   
3            4     ppl_100  act2_4109017  2023-08-26            type 2    NaN   
4            5     ppl_100   act2_898576  2023-08-04            type 4    NaN   
5            6  ppl_100002  act2_1233489  2022-11-23            type 2    NaN   
6            7  ppl_100002  act2_1623405  2022-11-23            type 2    NaN   
7            8  ppl_100003  act2_1111598  2023-02-07            type 2    NaN   
8            9  ppl_100003  act2_1177453  2023-06-28            type 2    NaN   
9           10  ppl_100003   act2_133509  2022-08-10            type 4    NaN   
10          11  ppl_100003  act2_1408475  2023-03-02            type 4    NaN   
11          12  ppl_100003  act2_1610829  2022-09-13            type 2    NaN   
12          13  ppl_100003  act2_1688731  2023-02-10            type 4    NaN   
13          14  ppl_100003  act2_1961720  2023-06-28            type 4    NaN   
14          15  ppl_100003  act2_1988351  2022-08-23            type 2    NaN   
15          16  ppl_100003  act2_2198176  2022-08-16            type 2    NaN   
16          17  ppl_100003  act2_2437661  2023-02-02            type 2    NaN   
17          18  ppl_100003  act2_2476911  2023-03-02            type 2    NaN   
18          19  ppl_100003  act2_2557270  2022-08-30            type 4    NaN   
19          20  ppl_100003  act2_2581989  2023-02-21            type 2    NaN   
20          21  ppl_100003  act2_3116385  2023-02-15            type 2    NaN   
21          22  ppl_100003  act2_3159712  2022-08-30            type 2    NaN   
22          23  ppl_100003  act2_3292005  2023-05-03            type 2    NaN   
23          24  ppl_100003  act2_3461867  2023-08-02            type 2    NaN   
24          25  ppl_100003  act2_3468306  2023-03-02            type 4    NaN   
25          26  ppl_100003  act2_3867292  2023-02-10            type 2    NaN   
26          27  ppl_100003  act2_3990676  2023-08-30            type 4    NaN   
27          28  ppl_100003  act2_4102292  2023-08-30            type 2    NaN   
28          29  ppl_100003  act2_4160587  2023-02-21            type 2    NaN   
29          30  ppl_100003  act2_4392666  2022-08-10            type 2    NaN   
..         ...         ...           ...         ...               ...    ...   
70          71  ppl_100025  act2_2942782  2022-09-16            type 5    NaN   
71          72  ppl_100025  act2_3094204  2022-09-29            type 2    NaN   
72          73  ppl_100025  act2_3235463  2022-09-16            type 5    NaN   
73          74  ppl_100025  act2_3280131  2022-08-26            type 2    NaN   
74          75  ppl_100025  act2_3349612  2023-01-10            type 5    NaN   
75          76  ppl_100025  act2_3422487  2022-09-15            type 5    NaN   
76          77  ppl_100025  act2_3509066  2022-11-26            type 5    NaN   
77          78  ppl_100025  act2_3524852  2022-09-23            type 2    NaN   
78          79  ppl_100025  act2_3571544  2022-11-27            type 5    NaN   
79          80  ppl_100025  act2_3707062  2022-09-15            type 5    NaN   
80          81  ppl_100025  act2_3727456  2023-01-12            type 5    NaN   
81          82  ppl_100025  act2_3897057  2022-09-16            type 5    NaN   
82          83  ppl_100025  act2_3907251  2022-09-15            type 5    NaN   
83          84  ppl_100025  act2_3981916  2023-01-11            type 5    NaN   
84          85  ppl_100025  act2_4100867  2022-09-15            type 5    NaN   
85          86  ppl_100025  act2_4182640  2022-09-16            type 5    NaN   
86          87  ppl_100025  act2_4337589  2023-01-11            type 5    NaN   
87          88  ppl_100025  act2_44

In [11]:
train.activity_category.describe()

count     1999999
unique          7
top        type 2
freq       814192
Name: activity_category, dtype: object

In [17]:
People.head(5)

people_id  char_1      group_1  char_2        date   char_3   char_4  \
0     ppl_100  type 2  group 17304  type 2  2021-06-29   type 5   type 5   
1  ppl_100002  type 2   group 8688  type 3  2021-01-06  type 28   type 9   
2  ppl_100003  type 2  group 33592  type 3  2022-06-10   type 4   type 8   
3  ppl_100004  type 2  group 22593  type 3  2022-07-20  type 40  type 25   
4  ppl_100006  type 2   group 6534  type 3  2022-07-27  type 40  type 25   

   char_5  char_6   char_7   ...    char_29 char_30  char_31  char_32  \
0  type 5  type 3  type 11   ...      False    True     True    False   
1  type 5  type 3  type 11   ...      False    True     True     True   
2  type 5  type 2   type 5   ...      False   False     True     True   
3  type 9  type 4  type 16   ...       True    True     True     True   
4  type 9  type 3   type 8   ...      False   False     True    False   

   char_33  char_34  char_35  char_36  char_37  char_38  
0    False     True     True     True    False       36  
1     True     True     True     True    False       76  
2     True     True    False     True     True       99  
3     True     True     True     True     True       76  
4    False    False     True     True    False       84  

[5 rows x 41 columns]

In [20]:
People.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189118 entries, 0 to 189117
Data columns (total 41 columns):
people_id    189118 non-null object
char_1       189118 non-null object
group_1      189118 non-null object
char_2       189118 non-null object
date         189118 non-null object
char_3       189118 non-null object
char_4       189118 non-null object
char_5       189118 non-null object
char_6       189118 non-null object
char_7       189118 non-null object
char_8       189118 non-null object
char_9       189118 non-null object
char_10      189118 non-null bool
char_11      189118 non-null bool
char_12      189118 non-null bool
char_13      189118 non-null bool
char_14      189118 non-null bool
char_15      189118 non-null bool
char_16      189118 non-null bool
char_17      189118 non-null bool
char_18      189118 non-null bool
char_19      189118 non-null bool
char_20      189118 non-null bool
char_21      189118 non-null bool
char_22      189118 non-null bool
char_23      18

In [5]:
test=pd.read_csv("C:/Users/Mahavir/Desktop/Customer Value Prediction/test.csv")

In [6]:
pd.value_counts(train.outcome)

0    1123190
1     876809
Name: outcome, dtype: int64

In [7]:
876809/1123190

0.7806417436052672

In [10]:
pd.value_counts(test.outcome)

1    98688
0    98603
Name: outcome, dtype: int64

In [12]:
98688/98603

1.0008620427370365

In [13]:
train.head(3)

Unnamed: 0 people_id   activity_id        date activity_category char_1  \
0           1   ppl_100  act2_2434093  2022-09-27            type 2    NaN   
1           2   ppl_100  act2_3404049  2022-09-27            type 2    NaN   
2           3   ppl_100  act2_3651215  2023-08-04            type 2    NaN   

  char_2 char_3 char_4 char_5 char_6 char_7 char_8 char_9 char_10  outcome  
0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  type 1        0  
1    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  type 1        0  
2    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  type 1        0

In [14]:
People.char_35

0          True
1          True
2         False
3          True
4          True
5          True
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23         True
24        False
25         True
26        False
27        False
28        False
29        False
          ...  
189088    False
189089     True
189090     True
189091    False
189092    False
189093    False
189094    False
189095     True
189096    False
189097    False
189098    False
189099    False
189100    False
189101    False
189102    False
189103    False
189104    False
189105    False
189106    False
189107     True
189108    False
189109    False
189110    False
189111    False
189112    False
189113    False
189114    False
189115    False
189116     True
189117    False
Name: char_35, Length: 1

In [32]:
x=[10,20,30,40]
y=[11,21,31,-1]

In [33]:
np.corrcoef(x,y)

array([[ 1.        , -0.24502148],
       [-0.24502148,  1.        ]])

In [27]:
x=[10,20,30,40]
y=[11,21,31,44]

In [29]:
np.corrcoef(x,y)

array([[1.        , 0.99773518],
       [0.99773518, 1.        ]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [1]:
import numpy as np

X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])

y = np.array([[0,1,1,0]]).T
alpha,hidden_dim = (0.5,4)

In [11]:
alpha,hidden_dim

(0.5, 4)

4

In [2]:

synapse_0 = 2*np.random.random((3,hidden_dim)) - 1

synapse_1 = 2*np.random.random((hidden_dim,1)) - 1

In [3]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [4]:
y

array([[0],
       [1],
       [1],
       [0]])

In [5]:
synapse_0

array([[-0.23356251, -0.03632229, -0.397067  ,  0.75432962],
       [-0.86824516,  0.24025102, -0.10880253, -0.70345021],
       [ 0.52192   , -0.37435286, -0.72907686,  0.98793853]])

In [6]:
synapse_1

array([[ 0.27691008],
       [ 0.26860781],
       [-0.43842322],
       [-0.95951766]])

In [14]:
for j in range(60000): 
    layer_1 = 1/(1+np.exp(-(np.dot(X,synapse_0))))
    layer_2 = 1/(1+np.exp(-(np.dot(layer_1,synapse_1))))
    layer_2_delta = (layer_2 - y)*(layer_2*(1-layer_2))
    layer_1_delta = layer_2_delta.dot(synapse_1.T) * (layer_1 * (1-layer_1))
    synapse_1 -= (alpha * layer_1.T.dot(layer_2_delta))    
    synapse_0 -= (alpha * X.T.dot(layer_1_delta))

In [15]:
synapse_1

array([[ 11.0754271 ],
       [  5.56633081],
       [ -1.01084562],
       [-10.76247702]])

In [17]:
?np.dot

In [27]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]


In [33]:
a[1]

[0, 1]

In [34]:
 np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [16]:
synapse_0 

array([[ 4.61703511,  3.74893579, -1.93997895,  7.41038653],
       [-6.87801767,  3.49473053, -1.51859015, -5.9662732 ],
       [-1.76072736,  0.02077055, -1.14438271,  2.62659271]])